######################## default configuration ####################
baseURL = "https://mitzu.io"
title = "Mitzu - Product Analytics Over Your Data Warehouse"
theme = ["bigspring"]
timeZone = "UTC"
paginate = "6" 
summaryLength = "10"
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
disableLanguages = [] # example: ["de"] for disable deutsch language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = true # If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content.

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.98.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 100

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#74A"
color_secondary = "#376f92"
body_color = "#fff"
text_color = "#777"
text_dark = "#222"
text_light = "#959595"
border_color = "#ECECEC"
dark_body_color = "#1E262C"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#fff"
dark_border_color = "#4e4e4e"
black = "#101418"
white = "#fff"
light = "#EDF6F5"
dark = "#1b2229"