# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Github"
url = "https://github.com/mitzu-io/mitzu"
weight = 3

[[main]]
weight = 4
name = "Community"
hasChildren = true

[[main]]
parent = "Community"
name = "Join our Slack"
url = "blog/"
weight = 1

[[main]]
parent = "Community"
name = "Contact us"
url = "contact/"
weight = 2


[[footer_right]]
name = "Contact"
url = "contact/"
weight = 2

[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4
